### ISSUE TITLE
Call to undefined function $autoid()

### ISSUE THREAD

**Issue by joernroeder** [bnomei/kirby3-autoid#8]
Hey Bruno,
just added an autoid field to a `file` blueprint. got the following error after on field change:

```
[Thu Sep  6 21:19:18 2018] Error: Call to undefined function o2ebf0gz() in /vendor/bnomei/kirby3-autoid/classes/AutoID.php:154
Stack trace:
#0 /vendor/bnomei/kirby3-autoid/classes/AutoID.php(430): Bnomei\AutoID::removeEntry('o2ebf0gz')
#1 /vendor/bnomei/kirby3-autoid/config.php(70): Bnomei\AutoID::removeFile(Object(Kirby\Cms\File))
#2 [internal function]: Kirby\Cms\App->{closure}(Object(Kirby\Cms\File), Object(Kirby\Cms\File))
#3 /vendor/getkirby/cms/src/Cms/App.php(890): Closure->call(Object(Kirby\Cms\App), Object(Kirby\Cms\File), Object(Kirby\Cms\File))
#4 /vendor/getkirby/cms/src/Cms/FileActions.php(103): Kirby\Cms\App->trigger('file.update:aft...', Object(Kirby\Cms\File), Object(Kirby\Cms\File))
#5 /vendor/getkirby/cms/src/Cms/ModelWithContent.php(239): Kirby\Cms\File->commit('update', Array, Object(Closure))
#6 /vendor/getkirby/cms/config/api/routes/pages.php(104): Kirby\Cms\ModelWithContent->update(Array)
#7 [internal function]: Kirby\Api\Api->{closure}('sponsors', 'ddtxoajuqaa8flw...')
#8 /vendor/getkirby/cms/src/Api/Api.php(71): Closure->call(Object(Kirby\Api\Api), 'sponsors', 'ddtxoajuqaa8flw...')
#9 /vendor/getkirby/cms/src/Api/Api.php(264): Kirby\Api\Api->call('pages/sponsors/...', 'PATCH', Array)
#10 /vendor/getkirby/cms/config/routes.php(53): Kirby\Api\Api->render('pages/sponsors/...', 'PATCH', Array)
#11 [internal function]: Kirby\Http\Route->{closure}('pages/sponsors/...')
#12 /vendor/getkirby/cms/src/Cms/App.php(186): Closure->call(Object(Kirby\Http\Route), 'pages/sponsors/...')
#13 /vendor/getkirby/cms/src/Cms/App.php(572): Kirby\Cms\App->call('api/pages/spons...', 'PATCH')
#14 /public/index.php(34): Kirby\Cms\App->render()
#15 /public/router.php(12): include('/absPath...')
#16 {main}
```

**Comment by bnomei** [comment]
did a fix a few days ago but had not time to create non-devit/composer zip. can you check if you have recent version? with this patched file...
https://github.com/bnomei/kirby3-autoid/commit/132adc816e159ff8402b1a14d1a4329c94b0b012

but do not let `1.0.0` distract you. just notices sematic version for pre 1.x works different with compser.
see https://github.com/bnomei/kirby3-autoid/issues/9

**Comment by bnomei** [comment]
this zip should be most current
https://github.com/bnomei/kirby3-autoid/releases/tag/v1.0.0

**Comment by bnomei** [comment]
@joernroeder so this is solved?

**Comment by joernroeder** [comment]
ah yes. totally forgot to close it. thx
